export const API_URL = "https://api.themoviedb.org/3/movie";
export const IMG_URL = "https://image.tmdb.org/t/p/original";

export const FETCH_MOVIE_LOADING = "FETCH_MOVIE_LOADING";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_ERROR = "FETCH_MOVIE_ERROR";

export const FETCH_MOVIE_LOADING_INFINITE_SCROLL =
  "FETCH_MOVIE_LOADING_INFINITE_SCROLL";
export const FETCH_MOVIE_SUCCESS_INFINITE_SCROLL =
  "FETCH_MOVIE_SUCCESS_INFINITE_SCROLL";
export const FETCH_MOVIE_ERROR_INFINITE_SCROLL =
  "FETCH_MOVIE_ERROR_INFINITE_SCROLL";
